### PR TITLE
#3714: Testlink not usable anymore after cookie size (request header) exceeds server limit

### PR DESCRIPTION
**Pull request by one-github**
http://mantis.testlink.org/view.php?id=3714

Implementation of a LocalStorage for the ExtJS state manager instead of cookies. I decided against a fallback to the cookie storage for reasons of simplicity and unnecessary bulk. All current browser generations support the HTML5 localStorage API: http://caniuse.com/#search=localstorage

### CODE REVIEW

**Comment by ChuckNorrison** [comment]
Thank you so much. Will give it a try :-)

**Comment by jamofer** [comment]
This issue is really annoying when you have a lot of test cases. It would be very nice to have this PR, any news from this?

**Comment by fmancardi** [comment]
No plans yet, but you can help applying it to your installation and
providing feedback.

Best regards

**Comment by fmancardi** [comment]
Merged manually into branch testlink_1_9_20_fixed

**Pull request closed without merging**
