### PR TITLE
Add/remove testcases navigation requirements

### PR DESCRIPTION
**Pull request by Tigeek**
Add functionnality in the "Add / Remove Test Cases" screen of the "Test Plan" the groupings are made by "test case", we had the need to sort them by "cover of requirement" and then add all Tests covering a requirement in the test plan.

### CODE REVIEW

**Comment by ChuckNorrison** [comment]
- A Tests Grouped by Option was added in Settings
- After selecting Req.Coverage, the tree structure changed to Requirements view
- After selecting a Requirement, nothing happens. The view on the right is still unchanged

Some Ideas? Anyway i think that could be useful if it works as expected, thanks.

**Comment by Tigeek** [comment]
I check and keep you informed.

**Comment by Tigeek** [comment]
Sorry, I have forget push 2 files.
I check by taking over the branch it works now.
Thanks.

**Comment by ChuckNorrison** [comment]
Great, now it works :)

**Comment by Tigeek** [comment]
Correction, display of the tree when clicking on the button "advanced filter"
and add litle functionnality, get the test cases covered by the child requirements, when you select a requirement.

**Comment by Tigeek** [comment]
Hi, 

What has been added:

1) addition of filtering in "requirements coverage" mode.
2) display of the documentation in the right-hand part to replace the abre in "requirements coverage" mode.


What it will be doing in the next few days:

1) creation of documentation.
2) translation of different labels into all languages.
3) Repair of the filter by test case number, when one is in the "requirement coverage" mode.

**Comment by fmancardi** [comment]
Hi
thanks for your work
I can not accept your pull requests this way with marks of where your code start and end.
I'm going to understand how to add your code to stable dev line

**Comment by Tigeek** [comment]
Hello, 

I understand you. I will clean the code and republish it in about ten days. 

Have a good day.

**Comment by fmancardi** [comment]
Please do not touch anything, I'm going to refactor the code, then I will contact you
have a nice week end

**Comment by Tigeek** [comment]
Ok. Thanks.

**Comment by fmancardi** [comment]
changes on  frmWorkArea.php => rejected

**Comment by fmancardi** [comment]
Please do not leave comments on code that are wrong, like author of method or function description. It's lot better to have no info that wrong info, because effort for maintenance increase to an unacceptable level

**Comment by Tigeek** [comment]
Sorry, i will be vigilant at this the next time.

**Comment by Tigeek** [comment]
The translation of the different label and the cleaning of the code has been done.

**Comment by Tigeek** [comment]
For information,
The link between the "parent / child" requirement is only made when clicking on a requirement, and not when clicking on a folder in order to avoid excessive loading times.

**Comment by MrBricodage** [comment]
Please explain which part is "a great mess". Code or commits?

I plan to provide a user manual with screenshots to explain what have been done in this branch from a user point of view (menus, options).

**Comment by fmancardi** [comment]
I prefer to explain in a private discussion via mail (thing that i've tried to do to coordinate development since the beggining of this development)

**Pull request merged**
