### PR TITLE
Defines and Image Path

### PR DESCRIPTION
**Pull request by ChuckNorrison**
- for define() and defined() you have to use single quotes
- Image path for Requirements based Report in Reports reverted

### CODE REVIEW

**Comment by fmancardi** [comment]
Hi:
thanks for your effort. There is an important thing about the pull requests comments. It's very important to provide details explaining what if the error you get without changes you are requesting .
- This is the case for your request 'Wrong path in Requirements ...' (commit e93ce11) regarding changes on getImageSet(), I can not consider it if you can not explain how I can reproduce the error.
- Regarding Fiz defines for TL_APICALL: define(), example on PHP shows that you can use double quotes.
 
I'm going to check your changes and understand best way to apply it .
regards

**Comment by ChuckNorrison** [comment]
**Wrong path in Requirements based Report:**
The images in "Requirements based Report" are broken

**Fix defines for TP_APICALL:**
There have to be quotes. Single quotes are common used. In lib/functions/common.php line 57 there are no quotes used. An error message is found in log.

**Custom $_SESSION path:**
Here it is possible to use several testlinks on one server.

**Comment by fmancardi** [comment]
Fix for TL_APICALL without single quotes done

**Comment by ChuckNorrison** [comment]
i will make single pull requests for each commit

**Pull request closed without merging**
