### PR TITLE
Copy the steps and execution notes for failed tc

### PR DESCRIPTION
**Pull request by delcroip**
if the test is failed,
if the step is not passed or there is an execution note then this is added to the "note/description"
Step {step number}({test status}): {step execution notes}

### CODE REVIEW

**Comment by fmancardi** [comment]
Thanks, important thing IMHO this need to be managed by a configuration option.
would you mind to propose name and do implementation -> default behaviour must be the old one

regards

**Comment by fmancardi** [comment]
Please also use a constant to express the FAILED value not the 'f', this will be improve code understanding without need of comments

thanks

**Comment by delcroip** [comment]
I'll check that

**Comment by delcroip** [comment]
@fmancardi with the new gui coming is there a preferred way to send the Param to the front end or having a checkbox (prechecked based on config) will be enough ?

**Comment by fmancardi** [comment]
We can start with a system wide config i.e. for all test projects, and as
you suggested set the value ( a yes/no select will be better than a
checkbox)
That user can change each time.
Another option will be to create a custom field that you can use at
testplan level, if it's present this will mean default value will be new
behaviour, is doen't old one.
Give a try to these alternatives.

Regards

Il Lun 29 Mar 2021, 19:07 Patrick Delcroix ***@***.***> ha
scritto:

**Comment by delcroip** [comment]
replaced by https://github.com/TestLinkOpenSourceTRMS/testlink-code/pull/320

**Pull request closed without merging**
