### PR TITLE
 Change status of all steps when changing global status of testcase

### PR DESCRIPTION
**Pull request by Kanaduchi**
Change status of all steps when changing global status of testcase

### CODE REVIEW

**Comment by fmancardi** [comment]
Hi
This is not what i want, an OPTION ON GUI that user can choose each time, not a config option => still no good to be added to stable code
You need to change the SMARTY TEMPLATE

**Comment by ChuckNorrison** [comment]
Please add a checkbox to update each step action result

**Comment by Kanaduchi** [comment]
I'm preparing pull request with checkbox.

I have 1 question - should I remove config section or left it and display this checkbox if $testcase_cfg->change_steps_exec_type = TRUE?

**Comment by fmancardi** [comment]
Please, remove it

**Comment by fmancardi** [comment]
I'm going to analize code and refactor it because a quick review spot confusing variable names.

**Comment by fmancardi** [comment]
In addition when planning an implementation is very important to try to understand what standard methods provide, and if needed propose a change to standard method instead of reusing existing and develop something in an Overkilled mode. Because at the end of the day, I need to refactor to much, then I've used anyway LOT OF TIME.

**Comment by fmancardi** [comment]
feature have been added but doing complete refactoring

**Pull request closed without merging**
