### PR TITLE
creating a Jira issue is fail

### PR DESCRIPTION
**Pull request by yihoyoung**
I want to create JIRA issue, but it always fails.

The reason lies in

1. The parameter of selectlist type was not passed to JIRA correctly

2. There is no userpicker type, only multiuserpicker type

### CODE REVIEW

**Comment by fmancardi** [comment]
thanks

**Comment by kenchan0130** [comment]
I would like comments on the source code to be written in the common language, English.

**Comment by fmancardi** [comment]
@kenchan0130 I've not checked the comments, I'm sorry I didn't expect comments in this way, going to remove

**Comment by fmancardi** [comment]
I've reverted the changes because
1. preg_grep() generates PHP Warning
2. it's not clear if customfield_10311 is standard and what is the human name

**Pull request merged**
