### PR TITLE
Fix TLSmarty constructor name

### PR DESCRIPTION
**Pull request by lifeofguenter**
- ignoring IDE specific config files as they are far too opinionated and shouldn't be in the repo
- removed those files/folders as well
- fixed `PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; TLSmarty has a deprecated constructor in /opt/testlink/html/lib/functions/tlsmarty.inc.php on line 110`
- most of the other changes are due to unnecessary whitespaces in the code

1. Aside from that, what is the strategy overall? I am seeing quite a few 3rd party libs out-of-date - maybe time to switch to composer, at least for the 3party stuff?
2. any automated tests? :trollface:

### CODE REVIEW

**Comment by fmancardi** [comment]
IMHO this is not the place to discuss strategies.

**Comment by fmancardi** [comment]
tlSmarty construct fixed.
useless (and harmless) files removed

**Comment by lifeofguenter** [comment]
seems like it was introduced back in here: https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/e281cbde9cb0f721fa620de508493214f25a790a

Any reason my PR was not merged in? Would like to improve my contribution for next time :)

**Comment by fmancardi** [comment]
I do not want introduce commits that convey fixes for different things, I try to work always as much atomic as possible. May be can considered an overkill. 

For this case I would have expect three PR: 
a) useless & harmless files 
b) PHP __constructor 
c) spaces.

This way I will be able in a simple way to accept according my evaluation.
That's why I've take your contribution and apply manually instead of accepting your PR
You have no wasted your time, only difference is that your contribution have been applied in a different way.

**Comment by lifeofguenter** [comment]
Thanks @fmancardi , noted for next time :)

**Pull request closed without merging**
