### PR TITLE
Fix bug of creation new builds

### PR DESCRIPTION
**Pull request by Kanaduchi**
Fix bug of creation new builds

### CODE REVIEW

**Comment by fmancardi** [comment]
if you do not provide better commit log is very difficult to understand what is been fixed.

**Comment by Kanaduchi** [comment]
Currently is is impossible to create new builds on 1.9.17 because of bug in commit:
https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/5e5de2edfd62f1bc44255325b7036f157acddda2

I fixed this problem. Please look at changed file. It is very simple fix

**Comment by fmancardi** [comment]
you have to explain and not request that i read the code

**Comment by Kanaduchi** [comment]
In https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/5e5de2edfd62f1bc44255325b7036f157acddda2 commit there is a bug with variable in buildView.tpl

According to Smarty templates engine we should wrap inside variables
So we should use
{$createAction="$managerURL?do_action=create&tplan_id={$gui->tplan_id}"}
instead of
{$createAction="$managerURL?do_action=create&tplan_id=$gui->tplan_id"}

So I prepared this fix

**Comment by fmancardi** [comment]
Thanks this is related to 8112: Creating a new build is not possible in latest Google Chrome due to security reasons and not closed HTML tag

**Pull request closed without merging**
