### PR TITLE
Added Microsoft OAuth provider

### PR DESCRIPTION
**Pull request by nickidw**
Changes to add Microsoft OAuth provider. Microsoft configuration does not allow redirect URL with querystring, which is how the current mechanism is built to work. This means a new php page (microsoftoauth.php) is required to receive the OAuth redirect after authentication. Testing using both Microsoft account as well as Azure AD account.

Also fixed bug where login screen was not drawn if OAuth authentication failed for some reason.

### CODE REVIEW

**Comment by fmancardi** [comment]
Hi
Thanks for your help.
In order to add this to the review process I need to ask you:

1. please create a ticket in mantis.testlink.org describing the new feature
2. please provide details about what is needed on the cloud side (i.e. you need to have an Office 365 account or what is really needed), in order to allow me to setup a testing environment.

I will wait for these before adding this to the review queu.

regards

**Comment by nickidw** [comment]
It's a pleasure. I did log a ticket, link is http://mantis.testlink.org/view.php?id=8591. Please let me know if more information is required.

Nicki

**Comment by fmancardi** [comment]
Would you mind to provide a configuration example on the microsofy account side ?
I need something like the steps to setup oauth when using google, where you use the google https://developers.google.com

thanks a lot

**Comment by nickidw** [comment]
I've added notes to the ticket explaining the process step by step. http://mantis.testlink.org/view.php?id=8591#c28580

**Comment by fmancardi** [comment]
Thanks

**Pull request merged**
