### PR TITLE
Navigation bar redesign

### PR DESCRIPTION
**Pull request by MichielVT**
Hi,

I've had a go at doing a redesign of the navigation bar.

Main changes:
- Title is now below the logo.
- buttons have a more tab-like look.
- User info and logout are on the extreme right side of the navbar. This is the layout that is currently used in many sites that require user login. So this will feel familiar to most users.
- Scales up and down nicely between 1024 and 1920 px on IE and chrome. I have not yet tried higher resolutions as I don't have a high res screen available.

Full text search is not yet included as this was not in testlink yet when I started working on this.

Please let me know what you think or if you see some possible improvements.

### CODE REVIEW

**Comment by ChuckNorrison** [comment]
Only common.php is changed here? 

My navigation bar is broken with this commit.

**Comment by fmancardi** [comment]
This Merge Requesta has not been accepted and will not be part of any stable release of TestLink at least in the near future

**Comment by MichielVT** [comment]
Hi,
thanks for checking.
Something must have gone wrong with the pull request as there were also changes in the template and CSS. I'll check when I am able.

Op 13 apr. 2017 11:44 schreef ChuckNorrison <notifications@github.com>:

Only common.php is changed here?

My navigation bar is broken with this commit.

**Comment by fmancardi** [comment]
Thanks for your help, but this does not fit on current design

**Pull request closed without merging**
