### PR TITLE
import customized theme's frame.css

### PR DESCRIPTION
**Pull request by philip1134**
3 files changed. 
change "...gui/themes/default/css/frame.css" to "...{$tlCfg->theme_dir}css/frame.css"

1. gui/templates/dashio/main.tpl 
```php
# <link rel="stylesheet" type="text/css" href="{$basehref}gui/themes/default/css/frame.css">
<link rel="stylesheet" type="text/css" href="{$basehref}{$tlCfg->theme_dir}css/frame.css">
```
_gui/themes/default/ -> {$tlCfg->theme_dir}_

2.  gui/templates/tl-classic/frmInner.tpl 
```php
# <link rel="stylesheet" type="text/css" href="{$basehref}gui/themes/default/css/frame.css">
<link rel="stylesheet" type="text/css" href="{$basehref}{$tlCfg->theme_dir}css/frame.css">
```
_gui/themes/default/ -> {$tlCfg->theme_dir}_

3.  gui/templates/tl-classic/main.tpl
```php
# <link rel="stylesheet" type="text/css" href="{$basehref}gui/themes/default/css/frame.css">
<link rel="stylesheet" type="text/css" href="{$basehref}{$smarty.const.TL_THEME_CSS_DIR}frame.css">
```
_gui/themes/default/css/ -> {$smarty.const.TL_THEME_CSS_DIR}_

### CODE REVIEW

**Comment by fmancardi** [comment]
A little bit better but these details explaim what not why or the feature provided.
Then potential advantages or drawbacks are not easily undertandable.
pr still will be not applied.

**Comment by philip1134** [comment]
> A little bit better but these details explaim what not why or the feature provided.
> Then potential advantages or drawbacks are not easily undertandable.
> pr still will be not applied.

frame.css is hard coded in all <link> tag, and point to "default" theme ( see "{$basehref}gui/themes/default/css/frame.css"）, if user want to use his customized theme, frame.css under his theme folder will not be loaded. so if changed to use $tlCfg->theme_dir which was configured in config file, user can load his owner frame.css.

**Comment by fmancardi** [comment]
Thanks a lot!

**Comment by fmancardi** [comment]
changes with slight review have been applied

**Comment by philip1134** [comment]
> changes with slight review have been applied

thanks a lot!

**Pull request closed without merging**
