### PR TITLE
Add missing options to XMLRPC createPlatform function

### PR DESCRIPTION
**Pull request by maksonlee**
Change-Id: I16edc7bca9f3b75f06eccac4fa6f83dc90fcf79b

### CODE REVIEW

**Comment by fmancardi** [comment]
would you mind to provide a simple detail of options added? 
(I know can be extracted from code but IMHO it's better to have a detail of the design )

**Comment by maksonlee** [comment]
> would you mind to provide a simple detail of options added?
> (I know can be extracted from code but IMHO it's better to have a detail of the design )

i have modified the commit message.

**Comment by fmancardi** [comment]
well the commit message still explain nothing=> going for the info into the code, it seems sometimes is better do not ask for help

**Comment by fmancardi** [comment]
thanks for contribution

**Pull request merged**
