### PR TITLE
Desktop page design : proposal (fix Mantis Issue 8266)

### PR DESCRIPTION
**Pull request by MrBricodage**

### CODE REVIEW

**Comment by fmancardi** [comment]
please provide a screenshot of the result of your changes.
Thanks

**Comment by fmancardi** [comment]
going to support it with a new theme.

**Comment by samsalas** [comment]
Will the legacy page change as well? I can help you if you want.

**Comment by MrBricodage** [comment]
Legacy page (blue background) is not available anymore.
This PR should be splitted between functional (new menus entries) and design (blocks titles)

Regards

-------- Message d'origine --------

**Comment by samsalas** [comment]
Ok. Thank you. Will definitely try it!

**Comment by MrBricodage** [comment]
Hi Francisco, 

I've seen the ability to define a new tpl for mainPage that you added 4 days ago in TestLink Code (commit 022c24d26c7f4d7ecef3249aa2a08ed74e7ff123).

Is this modification linked to this PR?

IMHO, different styles defined in different tpl will create fragmentation, because functional modifications in "official" mainPage (new entries, ...) should be manually reported in all custom mainPage. In the other hand, it seems difficult to split functional and design with smarty templates, at least for this mainPage.

What is your opinion about this? 

Could you please tell me why this PR couldn't be the "official" mainPage?
Is there a problem with functional modifications (new menus) ? Or Style (I tried to keep colors found in others pages) ?

Regards

Mr.B

**Comment by fmancardi** [comment]
I do not want old colors in the official  main page, right now I do not have enough time to install and play with your proposal. For me best thing will be (in future) provide a way to have / switch from one main page to other.
Right now also I've found the inventory access no matter this feature is enabled or not on test project (may be this is my mistake).

My commit on the chance to use custom mainPage is just to give this change but developer will understand all risks

**Comment by fmancardi** [comment]
closing dashio administrator template is the choice

**Pull request closed without merging**
